# Data 512 HW 2 (Raviprakash Rthvik, Student ID: 2272104, Email: rravipra@uw.edu)

# Combining the Datasets:

In [57]:
# import the required libraries
import pandas as pd
from tabulate import tabulate

Extracting the data as dataframes from the CSV files:

In [58]:
# get all the data that we have as CSV files (created by the previous code and also the ones that are provided)
df_ores_scores = pd.read_csv('/content/drive/MyDrive/ores_scores.csv') # created in get_ores_scores.ipynb
df_city_by_state = pd.read_csv('/content/drive/MyDrive/us_cities_by_state_SEPT.2023.csv') # provided and the link can be found in the ReadMe file
df_population = pd.read_excel('/content/drive/MyDrive/NST-EST2022-POP.xlsx', header=[2,3]) # link provided in the ReadMe file
df_states_region = pd.read_excel('/content/drive/MyDrive/US States by Region - US Census Bureau.xlsx') # provided and the link can be found in the ReadMe file

The dataframe containing the ORES scores.

In [59]:
# this is the dataframe of the ores scores that was extracted as a csv file through the LiftWing ML Service API
df_ores_scores

                     title      rev_id prediction
0       Abbeville, Alabama  1171163550          C
1      Adamsville, Alabama  1177621427          C
2         Addison, Alabama  1168359898          C
3           Akron, Alabama  1165909508         GA
4       Alabaster, Alabama  1179139816          C
...                    ...         ...        ...
22147   Wamsutter, Wyoming  1169591845         GA
22148   Wheatland, Wyoming  1176370621         GA
22149     Worland, Wyoming  1166347917         GA
22150      Wright, Wyoming  1166334449         GA
22151       Yoder, Wyoming  1171182284          C

[22152 rows x 3 columns]

The dataframe of the city by state:

In [60]:
# the dataframe of the city by state:
df_city_by_state

,state,page_title,url
0,Alabama,"Abbeville, Alabama","https://en.wikipedia.org/wiki/Abbeville,_Alabama"
1,Alabama,"Adamsville, Alabama","https://en.wikipedia.org/wiki/Adamsville,_Alabama"
2,Alabama,"Addison, Alabama","https://en.wikipedia.org/wiki/Addison,_Alabama"
3,Alabama,"Akron, Alabama","https://en.wikipedia.org/wiki/Akron,_Alabama"
4,Alabama,"Alabaster, Alabama","https://en.wikipedia.org/wiki/Alabaster,_Alabama"
...,...,...,...
22152,Wyoming,"Wamsutter, Wyoming","https://en.wikipedia.org/wiki/Wamsutter,_Wyoming"
22153,Wyoming,"Wheatland, Wyoming","https://en.wikipedia.org/wiki/Wheatland,_Wyoming"
22154,Wyoming,"Worland, Wyoming","https://en.wikipedia.org/wiki/Worland,_Wyoming"
22155,Wyoming,"Wright, Wyoming","https://en.wikipedia.org/wiki/Wright,_Wyoming"
22156,Wyoming,"Yoder, Wyoming","https://en.wikipedia.org/wiki/Yoder,_Wyoming"

Population dataframe by Geographic area and the states:

In [61]:
# the dataframe of the geographic area and the population estimates of the years 2020, 2021 and 2022 where we only need the one from 2022 when we merge with the other datasets.
df_population

                                      Geographic Area  \
                                   Unnamed: 0_level_1
0                                       United States
1                                           Northeast
2                                             Midwest
3                                               South
4                                                West
..                                                ...
58  Note: The estimates are developed from a base ...
59                                Suggested Citation:
60  Annual Estimates of the Resident Population fo...
61    Source: U.S. Census Bureau, Population Division
62                        Release Date: December 2022

   April 1, 2020 Estimates Base Population Estimate (as of July 1)  \
             Unnamed: 1_level_1                               2020
0                   331449520.0                        331511512.0
1                    57609156.0                         57448898.0
2                    68985537.0                         68961043.0
3                   126266262.0                        126450613.0
4                    78588565.0                         78650958.0
..                          ...                                ...
58                          NaN                                NaN
59                          NaN                                NaN
60                          NaN                                NaN
61                          NaN                                NaN
62                          NaN                                NaN


           2021         2022
0   332031554.0  333287557.0
1    57259257.0   57040406.0
2    68836505.0   68787595.0
3   127346029.0  128716192.0
4    78589763.0   78743364.0
..          ...          ...
58          NaN          NaN
59          NaN          NaN
60          NaN          NaN
61          NaN          NaN
62          NaN          NaN

[63 rows x 5 columns]

In [62]:
# Remove any leading dots in the 'Geographic Area' column to match the 'state' column
df_population.columns = ['Geographic Area', 'April 1, 2020', '2020', '2021', '2022']

# We just need the latest population that is from 2022
population_df = df_population[['Geographic Area', '2022']].rename(columns={'2022': 'Population'})

# Doing data manipulation to just extract the required rows (Please check out the CSV file which will give you an idea of why I am using this particular code to extract the Geographic area and the population)
population_df = population_df.iloc[:58,:].dropna().reset_index().drop(columns = 'index')

population_df

          Geographic Area   Population
0           United States  333287557.0
1               Northeast   57040406.0
2                 Midwest   68787595.0
3                   South  128716192.0
4                    West   78743364.0
5                .Alabama    5074296.0
6                 .Alaska     733583.0
7                .Arizona    7359197.0
8               .Arkansas    3045637.0
9             .California   39029342.0
10              .Colorado    5839926.0
11           .Connecticut    3626205.0
12              .Delaware    1018396.0
13  .District of Columbia     671803.0
14               .Florida   22244823.0
15               .Georgia   10912876.0
16                .Hawaii    1440196.0
17                 .Idaho    1939033.0
18              .Illinois   12582032.0
19               .Indiana    6833037.0
20                  .Iowa    3200517.0
21                .Kansas    2937150.0
22              .Kentucky    4512310.0
23             .Louisiana    4590241.0
24                 .Maine    1385340.0
25              .Maryland    6164660.0
26         .Massachusetts    6981974.0
27              .Michigan   10034113.0
28             .Minnesota    5717184.0
29           .Mississippi    2940057.0
30              .Missouri    6177957.0
31               .Montana    1122867.0
32              .Nebraska    1967923.0
33                .Nevada    3177772.0
34         .New Hampshire    1395231.0
35            .New Jersey    9261699.0
36            .New Mexico    2113344.0
37              .New York   19677151.0
38        .North Carolina   10698973.0
39          .North Dakota     779261.0
40                  .Ohio   11756058.0
41              .Oklahoma    4019800.0
42                .Oregon    4240137.0
43          .Pennsylvania   12972008.0
44          .Rhode Island    1093734.0
45        .South Carolina    5282634.0
46          .South Dakota     909824.0
47             .Tennessee    7051339.0
48                 .Texas   30029572.0
49                  .Utah    3380800.0
50               .Vermont     647064.0
51              .Virginia    8683619.0
52            .Washington    7785786.0
53         .West Virginia    1775156.0
54             .Wisconsin    5892539.0
55               .Wyoming     581381.0
56           .Puerto Rico    3221789.0

The dataframe of the states by region:

In [63]:
# use fillna to fill the NA values with the Division and the Region using the 'ffill' method
# We use this since in the CSV file the every region and division are only shown once (i.e for a set of states if it belongs to a particular division and a region
# for all those states the region and division are mentioned only once)

df_states_region["REGION"].fillna(method="ffill", inplace=True)
df_states_region["DIVISION"].fillna(method="ffill", inplace=True)

# reset the index
df_states_region = df_states_region.dropna().reset_index().drop(columns = 'index')
df_states_region

       REGION            DIVISION           STATE
0   Northeast         New England     Connecticut
1   Northeast         New England           Maine
2   Northeast         New England   Massachusetts
3   Northeast         New England   New Hampshire
4   Northeast         New England    Rhode Island
5   Northeast         New England         Vermont
6   Northeast     Middle Atlantic      New Jersey
7   Northeast     Middle Atlantic        New York
8   Northeast     Middle Atlantic    Pennsylvania
9     Midwest  East North Central        Illinois
10    Midwest  East North Central         Indiana
11    Midwest  East North Central        Michigan
12    Midwest  East North Central            Ohio
13    Midwest  East North Central       Wisconsin
14    Midwest  West North Central            Iowa
15    Midwest  West North Central          Kansas
16    Midwest  West North Central       Minnesota
17    Midwest  West North Central        Missouri
18    Midwest  West North Central        Nebraska
19    Midwest  West North Central    North Dakota
20    Midwest  West North Central    South Dakota
21      South      South Atlantic        Delaware
22      South      South Atlantic         Florida
23      South      South Atlantic         Georgia
24      South      South Atlantic        Maryland
25      South      South Atlantic  North Carolina
26      South      South Atlantic  South Carolina
27      South      South Atlantic        Virginia
28      South      South Atlantic   West Virginia
29      South  East South Central         Alabama
30      South  East South Central        Kentucky
31      South  East South Central     Mississippi
32      South  East South Central       Tennessee
33      South  West South Central        Arkansas
34      South  West South Central       Louisiana
35      South  West South Central        Oklahoma
36      South  West South Central           Texas
37       West            Mountain         Arizona
38       West            Mountain        Colorado
39       West            Mountain           Idaho
40       West            Mountain         Montana
41       West            Mountain          Nevada
42       West            Mountain      New Mexico
43       West            Mountain            Utah
44       West            Mountain         Wyoming
45       West             Pacific          Alaska
46       West             Pacific      California
47       West             Pacific          Hawaii
48       West             Pacific          Oregon
49       West             Pacific      Washington

In [64]:
# Define a mapping for state name conversions (this is to make sure that we are able to merge with the df_ores_scores dataframe
# and for the states to have the same names without any additional punctuations)

state_name_mapping = {
    'Georgia_(U.S._state)': 'Georgia',
    'New_Hampshire': 'New Hampshire',
    'New_Jersey': 'New Jersey',
    'New_Mexico': 'New Mexico',
    'New_York': 'New York',
    'North_Carolina': 'North Carolina',
    'North_Dakota': 'North Dakota',
    'Rhode_Island': 'Rhode Island',
    'South_Carolina': 'South Carolina',
    'South_Dakota': 'South Dakota',
    'West_Virginia': 'West Virginia'
}

# Apply the state name mapping to map the state names to the appropriate ones mentioned above:

df_city_by_state['state'] = df_city_by_state['state'].replace(state_name_mapping)

Merge all the dataframes together to get the desired dataframe

In [65]:
# Clean state names in population_df using the strip function (please refer to population_df above to see why I am doing this)
population_df['Geographic Area'] = population_df['Geographic Area'].str.strip('.').str.strip()

# Clean state names in df_city_by_state
df_city_by_state['state'] = df_city_by_state['state'].str.strip()

df_ores_scores['rev_id'] = df_ores_scores['rev_id'].astype(str)

# Merge df_city_by_state with df_ores_scores
merged_df = df_city_by_state.merge(df_ores_scores, left_on="page_title", right_on="title", how="left")

# Merge with population_df to add population data
merged_df = merged_df.merge(population_df, left_on="state", right_on="Geographic Area", how="left")

# Merge with df_states_region to add regional-division data
merged_df = merged_df.merge(df_states_region, left_on="state", right_on="STATE", how="left")

# Identify unmatched areas
unmatched_areas = merged_df[merged_df["DIVISION"].isna()]["state"].unique()

# Filter out non-state entries
valid_states = merged_df[~merged_df["state"].isin(unmatched_areas)]

# Create the final consolidated DataFrame
final_df = valid_states[["state", "DIVISION", "Population", "page_title", "rev_id", "prediction"]]

In [66]:
final_df = final_df.drop_duplicates().reset_index().drop(columns = 'index').dropna()
final_df = final_df.rename(columns = {'DIVISION':'regional_division', 'Population': 'population', 'page_title': 'article_title', 'rev_id':'revision_id',
                           'prediction': 'article_quality'})
final_df = final_df[['state', 'regional_division', 'population', 'article_title', 'revision_id', 'article_quality']]

In [67]:
final_df.to_csv('wp_scored_city_articles_by_state.csv', index=False)

#Analysis:

The analysis will consist of calculating total-articles-per-population (a ratio representing the number of articles per person)  and high-quality-articles-per-population (a ratio representing the number of high quality articles per person) on a state-by-state and divisional basis. All of these values are “per capita” ratios.
Consider "high quality" articles to be articles that ORES predicted would be in either the "FA" (featured article) or "GA" (good article) classes.

In [68]:
# Define what high quality articles are in this case: We are considering "high quality" articles to be articles that ORES predicted
# would be in either the "FA" (featured article) or "GA" (good article) classes
high_quality_articles = final_df[final_df['article_quality'].isin(['FA', 'GA'])]

# Group by state and count articles
state_article_counts = final_df.groupby('state').size()
state_high_quality_article_counts = high_quality_articles.groupby('state').size()

In [69]:
state_population = final_df.drop_duplicates(subset='state')[['state', 'population']].set_index('state')

# calculate the per capita ratios for each state based on the number of articles
state_articles_per_capita = state_article_counts / state_population['population']

# calculate the per capita ratios for each stata based on the high quality articles
state_high_quality_articles_per_capita = state_high_quality_article_counts / state_population['population']

#Questions to answer: Produce tables for

1) Top 10 US states by coverage: The 10 US states with the highest total articles per capita (in descending order).

2) Bottom 10 US states by coverage: The 10 US states with the lowest total articles per capita (in ascending order).

3) Top 10 US states by high quality: The 10 US states with the highest high quality articles per capita (in descending order).

4) Bottom 10 US states by high quality: The 10 US states with the lowest high quality articles per capita (in ascending order).

5) Census divisions by total coverage: A rank ordered list of US census divisions (in descending order) by total articles per capita.

6) Census divisions by high quality coverage: Rank ordered list of US census divisions (in descending order) by high quality articles per capita.#

In [70]:
# Get the top 10 states by coverage
top_10_states_by_coverage = state_articles_per_capita.sort_values(ascending=False).head(10)

# get the bottom 10 states by coverage
bottom_10_states_by_coverage = state_articles_per_capita.sort_values(ascending=True).head(10)

# get the top 10 states by high quality
top_10_states_by_high_quality = state_high_quality_articles_per_capita.sort_values(ascending=False).head(10)

# get the bottom 10 states by high quality
bottom_10_states_by_high_quality = state_high_quality_articles_per_capita.sort_values(ascending=True).head(10)

#1) Top 10 states by coverage

In [71]:
# Convert the series into a DataFrame and reset the index
df_top_10 = top_10_states_by_coverage.reset_index()
df_top_10.columns = ['State', 'Coverage']

# Make the rank as the index
df_top_10.index = range(1, len(df_top_10) + 1)

# Print using tabulate
print(tabulate(df_top_10, headers='keys', tablefmt='pipe'))

|    | State         |    Coverage |
|---:|:--------------|------------:|
|  1 | Vermont       | 0.00050845  |
|  2 | North Dakota  | 0.000456843 |
|  3 | Maine         | 0.000348651 |
|  4 | South Dakota  | 0.000341824 |
|  5 | Iowa          | 0.000325572 |
|  6 | Alaska        | 0.000203113 |
|  7 | Pennsylvania  | 0.000196963 |
|  8 | Michigan      | 0.000176697 |
|  9 | Wyoming       | 0.000170284 |
| 10 | New Hampshire | 0.000167714 |

#2) Bottom 10 States by coverage:

In [72]:
# Convert the series into a DataFrame and reset the index
df_bottom_10 = bottom_10_states_by_coverage.reset_index()
df_bottom_10.columns = ['State', 'Coverage']

# Make the rank as the index
df_bottom_10.index = range(1, len(df_bottom_10) + 1)

# Print using tabulate
print(tabulate(df_bottom_10, headers='keys', tablefmt='pipe'))

|    | State          |    Coverage |
|---:|:---------------|------------:|
|  1 | North Carolina | 4.67335e-06 |
|  2 | Nevada         | 5.97903e-06 |
|  3 | California     | 1.23497e-05 |
|  4 | Arizona        | 1.23655e-05 |
|  5 | Virginia       | 1.53162e-05 |
|  6 | Florida        | 1.85212e-05 |
|  7 | Oklahoma       | 1.86576e-05 |
|  8 | Kansas         | 2.14494e-05 |
|  9 | Maryland       | 2.54677e-05 |
| 10 | Wisconsin      | 3.25836e-05 |

# 3) Top 10 states by high quality

In [73]:
# Convert the series into a DataFrame and reset the index
df_top_10_high_quality = top_10_states_by_high_quality.reset_index()
df_top_10_high_quality.columns = ['State', 'Quality']

# Make the rank as the index
df_top_10_high_quality.index = range(1, len(df_top_10_high_quality) + 1)

# Print using tabulate
print(tabulate(df_top_10_high_quality, headers='keys', tablefmt='pipe'))

|    | State         |     Quality |
|---:|:--------------|------------:|
|  1 | Vermont       | 6.95449e-05 |
|  2 | Wyoming       | 6.70817e-05 |
|  3 | South Dakota  | 6.15504e-05 |
|  4 | West Virginia | 5.91497e-05 |
|  5 | Montana       | 4.89818e-05 |
|  6 | New Hampshire | 4.51538e-05 |
|  7 | Pennsylvania  | 4.36324e-05 |
|  8 | Missouri      | 4.25707e-05 |
|  9 | Alaska        | 4.22583e-05 |
| 10 | New Jersey    | 4.09212e-05 |

# 4) Bottom 10 states by high quality

In [74]:
# Convert the series into a DataFrame and reset the index
df_bottom_10_high_quality = bottom_10_states_by_high_quality.reset_index()
df_bottom_10_high_quality.columns = ['State', 'Quality']

# Make the rank as the index
df_bottom_10_high_quality.index = range(1, len(df_bottom_10_high_quality) + 1)

# Print using tabulate
print(tabulate(df_bottom_10_high_quality, headers='keys', tablefmt='pipe'))

|    | State          |     Quality |
|---:|:---------------|------------:|
|  1 | North Carolina | 1.96281e-06 |
|  2 | Virginia       | 2.07287e-06 |
|  3 | Nevada         | 2.51749e-06 |
|  4 | Arizona        | 3.26123e-06 |
|  5 | California     | 4.43256e-06 |
|  6 | Florida        | 5.34956e-06 |
|  7 | New York       | 5.59024e-06 |
|  8 | Maryland       | 6.81303e-06 |
|  9 | Kansas         | 7.49025e-06 |
| 10 | Oklahoma       | 7.71183e-06 |

We need to do some data manipulation which is to get the sum of the populations based on the divsion and then calculating the per capita ratios which is done below:

In [75]:
# Get the unique population for each state
state_population = final_df.drop_duplicates(subset='state').set_index('state')['population']

# Compute the total population for each division
division_population = final_df.drop_duplicates(subset='state').groupby('regional_division')['population'].sum()

# Group by regional_division and count total and high-quality articles
division_article_counts = final_df.groupby('regional_division').size()
division_high_quality_article_counts = high_quality_articles.groupby('regional_division').size()

# The articles-per-capita and high-quality-articles-per-capita for each division
division_articles_per_capita = division_article_counts / division_population
division_high_quality_articles_per_capita = division_high_quality_article_counts / division_population

# Rank divisions by articles per capita and high-quality articles per capita
division_rank_by_total = division_articles_per_capita.sort_values(ascending=False)
division_rank_by_hq = division_high_quality_articles_per_capita.sort_values(ascending=False)

#5) Census division by total coverage

In [76]:
# Convert the series to a list of tuples with rank
table_data_total = [(index+1, division, value) for index, (division, value) in enumerate(division_rank_by_total.items())]

# Print the table
print("Divisions ranked by total articles per capita:\n")
print(tabulate(table_data_total, headers=['Rank', 'Division', 'Articles per Capita'], tablefmt='pipe', floatfmt=("", ".", ".6f")))

Divisions ranked by total articles per capita:

|   Rank | Division           |   Articles per Capita |
|-------:|:-------------------|----------------------:|
|      1 | West North Central |              0.000181 |
|      2 | New England        |              0.000125 |
|      3 | East North Central |              0.000101 |
|      4 | Middle Atlantic    |              0.000090 |
|      5 | East South Central |              0.000078 |
|      6 | West South Central |              0.000050 |
|      7 | Mountain           |              0.000047 |
|      8 | South Atlantic     |              0.000028 |
|      9 | Pacific            |              0.000024 |

#6) Census division by high quality coverage

In [77]:
# Convert the series to a list of tuples with rank
table_data_total_by_hq = [(index+1, division, value) for index, (division, value) in enumerate(division_rank_by_hq.items())]

# Print the table
print("Divisions ranked by high quality articles per capita:\n")
print(tabulate(table_data_total_by_hq, headers=['Rank', 'Division', 'Articles per Capita'], tablefmt='pipe', floatfmt=("", ".", ".6f")))

Divisions ranked by high quality articles per capita:

|   Rank | Division           |   Articles per Capita |
|-------:|:-------------------|----------------------:|
|      1 | West North Central |              0.000033 |
|      2 | Middle Atlantic    |              0.000025 |
|      3 | New England        |              0.000020 |
|      4 | East South Central |              0.000016 |
|      5 | East North Central |              0.000015 |
|      6 | West South Central |              0.000015 |
|      7 | Mountain           |              0.000013 |
|      8 | Pacific            |              0.000009 |
|      9 | South Atlantic     |              0.000008 |